# Generated by Django 4.1.6 on 2023-12-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RESTapp', '0005_rename_category_book_categoty_book_book_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Categoty',
            new_name='category',
        ),
    ]
